version: '3.8'

services:
  app:
    build: .
    container_name: final_projesi_app
    env_file: .env
    volumes:
      - ./reports:/app/reports
    networks:
   - proje_agi
networks:
  proje_agi:
    driver: bridge

  # Uncomment to add a database
  # db:
  #   image: postgres:16-alpine
  #   env_file: .env
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
